# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dataverse.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dataverse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61taverse.proto\"F\n\x0fRelocateRequest\x12\x0f\n\x07\x43ontent\x18\x01 \x01(\x0c\x12\x10\n\x08\x46ilename\x18\x02 \x01(\t\x12\x10\n\x08Username\x18\x03 \x01(\t\"\"\n\x10RelocateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"o\n\x12ImageUploadRequest\x12\x0f\n\x07\x43ontent\x18\x01 \x01(\x0c\x12\n\n\x02Id\x18\x02 \x01(\t\x12*\n\nStatusCode\x18\x03 \x01(\x0e\x32\x16.ImageUploadStatusCode\x12\x10\n\x08Username\x18\x04 \x01(\t\"\x89\x01\n\x13ImageUploadResponse\x12\n\n\x02Id\x18\x01 \x01(\t\x12*\n\nStatusCode\x18\x02 \x01(\x0e\x32\x16.ImageUploadStatusCode\x12\x0f\n\x07Message\x18\x03 \x01(\t\x12\x10\n\x08Username\x18\x04 \x01(\t\x12\x17\n\x0fnodeConnections\x18\x05 \x03(\t\"3\n\rSearchRequest\x12\x10\n\x08\x46ilename\x18\x01 \x01(\t\x12\x10\n\x08Username\x18\x02 \x01(\t\"W\n\x0eSearchResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\t\x12\x17\n\x0fnodeConnections\x18\x02 \x03(\t\x12\x0f\n\x07\x43ontent\x18\x03 \x01(\x0c\x12\x0c\n\x04\x46ile\x18\x04 \x01(\t\"\x1f\n\rConfigRequest\x12\x0e\n\x06Server\x18\x01 \x01(\t\" \n\x0e\x43onfigResponse\x12\x0e\n\x06Status\x18\x01 \x01(\t*H\n\x15ImageUploadStatusCode\x12\x06\n\x02Ok\x10\x00\x12\n\n\x06\x46\x61iled\x10\x01\x12\x0b\n\x07Unknown\x10\x02\x12\x0e\n\nInProgress\x10\x03\x32\xcf\x01\n\x07Greeter\x12\x37\n\x06Upload\x12\x13.ImageUploadRequest\x1a\x14.ImageUploadResponse\"\x00(\x01\x12+\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\"\x00\x12+\n\x06\x43onfig\x12\x0e.ConfigRequest\x1a\x0f.ConfigResponse\"\x00\x12\x31\n\x08Relocate\x12\x10.RelocateRequest\x1a\x11.RelocateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataverse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEUPLOADSTATUSCODE']._serialized_start=589
  _globals['_IMAGEUPLOADSTATUSCODE']._serialized_end=661
  _globals['_RELOCATEREQUEST']._serialized_start=19
  _globals['_RELOCATEREQUEST']._serialized_end=89
  _globals['_RELOCATERESPONSE']._serialized_start=91
  _globals['_RELOCATERESPONSE']._serialized_end=125
  _globals['_IMAGEUPLOADREQUEST']._serialized_start=127
  _globals['_IMAGEUPLOADREQUEST']._serialized_end=238
  _globals['_IMAGEUPLOADRESPONSE']._serialized_start=241
  _globals['_IMAGEUPLOADRESPONSE']._serialized_end=378
  _globals['_SEARCHREQUEST']._serialized_start=380
  _globals['_SEARCHREQUEST']._serialized_end=431
  _globals['_SEARCHRESPONSE']._serialized_start=433
  _globals['_SEARCHRESPONSE']._serialized_end=520
  _globals['_CONFIGREQUEST']._serialized_start=522
  _globals['_CONFIGREQUEST']._serialized_end=553
  _globals['_CONFIGRESPONSE']._serialized_start=555
  _globals['_CONFIGRESPONSE']._serialized_end=587
  _globals['_GREETER']._serialized_start=664
  _globals['_GREETER']._serialized_end=871
# @@protoc_insertion_point(module_scope)
